NoteBoardApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('all/', views.AllNotesView.as_view(), name='all_notes'),
    # ajax
    path('ajax/', views.note_action_ajax, name='note_action_ajax'),

    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('add_note/', views.AddNoteView.as_view(), name='add_note'),
    path('add_note/<str:category_name>/', views.AddNoteView.as_view(), name='add_note_category'),
    path('<str:category_name>/', views.CategoryView.as_view(), name='category'), # ошибка в консоле
    path('search/<str:keyword>/', views.SearchView.as_view(), name='search'),
    path('delete_category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('delete_note/<int:pk>/', views.DeleteNote.as_view(), name='delete_note'),
    path('detail/<int:pk>/', views.DetailNoteView.as_view(), name='detail_note'),
]

TooDoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('NoteBoardApp.urls')),
]

NoteBoardApp/models.py
from django.db import models
from UserApp.models import User
from django.utils import timezone
from django.contrib.sessions.models import Session

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_category', verbose_name='Пользователь')
    name = models.CharField(max_length=30, verbose_name='Название категории')
    color = models.CharField(max_length=7, blank=True, null=True, verbose_name='Цвет')
    is_active = models.BooleanField(default=True, verbose_name='Активна')

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return self.name

class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_note', verbose_name='Пользователь')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    #text = models.TextField(verbose_name='Текст')
    deadline = models.DateTimeField(blank=True, null=True, default=timezone.datetime.now().replace(microsecond=0), verbose_name='Дата и время выполнения')
    is_done = models.BooleanField(default=False, verbose_name='Выполнено')

    class Meta:
        ordering = ['category', 'deadline', ]
        verbose_name = 'Заметка'
        verbose_name_plural = 'Заметки'

    def __str__(self):
        return self.title


# class UserSession(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     session = models.ForeignKey(Session, on_delete=models.CASCADE)

NoteBoardApp/forms.py
from django import forms
from django.forms.widgets import TextInput, DateTimeInput
from .models import Category, Note
from django.contrib.admin.widgets import AdminSplitDateTime


class CustomAdminSplitDateTime(AdminSplitDateTime):
    """Кастомный административный виджет без заголовков перед формой"""
    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        del context['date_label'], context['time_label']
        return context


class AddCategoryFrom(forms.ModelForm):
    color = forms.CharField(max_length=7, widget=TextInput(attrs={'type': 'color'}))

    class Meta:
        model = Category
        fields = ['name', 'color', ]


class AddNoteForm(forms.ModelForm):
    deadline = forms.SplitDateTimeField(input_date_formats=['%Y-%m-%d'], widget=CustomAdminSplitDateTime())
    class Meta:
        model = Note
        fields = ['title', 'category', 'deadline']


class UpdateNoteForm(forms.ModelForm):
    # deadline = forms.SplitDateTimeField(widget=DateTimeInput(attrs={'type': 'datetime'}))
    deadline = forms.SplitDateTimeField(input_date_formats=['%Y-%m-%d'], widget=CustomAdminSplitDateTime())
    class Meta:
        model = Note
        fields = ['title', 'category', 'deadline']

class SettingsForm(forms.Form):
    title = forms.CharField(max_length=7)

NoteBoardApp/views.py
from django.shortcuts import redirect, render
from .models import Category, Note
from UserApp.models import User
from django.utils import timezone
from django.http import JsonResponse
from django.views.generic import ListView, FormView, DeleteView, UpdateView
from .forms import AddCategoryFrom, AddNoteForm, UpdateNoteForm, SettingsForm
from .calculation import get_popular_category
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse_lazy
from .config import SiteTheme


class HomeView(ListView):
    """Вывод заметок на сегоднешний день"""
    model = Note
    template_name = 'NoteBoardApp/home.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # получение заметок на сегоднешний день
        context['datetime'] = timezone.datetime.now().day
        context['notes'] = Note.objects.filter(user=self.request.user, deadline__day=timezone.datetime.now().day)
        return context


def note_action_ajax(request):
    """Редактирование заметки полученной Ajax"""
    if request.is_ajax():
        data = request.GET
        note = Note.objects.get(id=data['checked'])
        if note.is_done:
            note.is_done = False
        else:
            note.is_done = True
        note.save(update_fields=['is_done'])
    return JsonResponse({'success': 'success'})


class AllNotesView(ListView):
    model = Note
    template_name = 'NoteBoardApp/all_notes.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # получение заметок за все время
        context['notes'] = Note.objects.filter(user=self.request.user).order_by('-deadline__date',
                                                                                'category__name',
                                                                                'deadline__time').distinct()
        return context


class CategoryView(ListView):
    model = Note
    template_name = 'NoteBoardApp/category.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        category_name = self.kwargs.get('category_name')
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(user=self.request.user, name=category_name)
        # Вычисление позиции нужной категории в списке всех категорий
        context['position'] = [category.name for category in Category.objects.filter(user=self.request.user)].index(category_name)
        context['notes'] = Note.objects.filter(user=self.request.user, category__name=category_name).order_by('-deadline')
        return context


class SearchView(ListView):
    model = Note
    template_name = 'NoteBoardApp/search.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        keyword = self.kwargs.get('keyword')
        context = super().get_context_data(**kwargs)
        context['keyword'] = keyword
        context['notes'] = Note.objects.filter(Q(user=self.request.user) & Q(title__icontains=keyword))
        return context


class AddCategoryView(FormView):
    form_class = AddCategoryFrom
    template_name = 'NoteBoardApp/add_category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['popular_category'] = get_popular_category(Category)
        return context

    def form_valid(self, form):
        form = form.save(commit=False)
        if form.name not in [i.name for i in Category.objects.filter(user=self.request.user)]:
            form.user = User.objects.get(email=self.request.user)
            form.save()
            return redirect('add_category')
        else:
            messages.error(self.request, 'Такая категория уже существует!')
            return redirect('add_category')

class DeleteCategory(DeleteView):
    model = Category
    template_name = 'NoteBoardApp/delete_category.html'
    success_url = reverse_lazy('home')

class AddNoteView(FormView):
    form_class = AddNoteForm
    template_name = 'NoteBoardApp/add_note.html'

    def get_initial(self):
        initial = super().get_initial()
        if self.kwargs.get('category_name') != None: # проверка 'необязательного' url параметра
            category_name = self.kwargs.get('category_name')
            initial['category'] = Category.objects.get(user=self.request.user, name=category_name)
            return initial

    def form_valid(self, form):
        note_id = self.kwargs.get('pk')
        form = form.save(commit=False)
        form.user = User.objects.get(email=self.request.user)
        form.save()
        return redirect('category', form.category)

class DeleteNote(DeleteView):
    model = Note
    template_name = 'NoteBoardApp/delete_note.html'
    success_url = reverse_lazy('home')

class DetailNoteView(UpdateView):
    model = Note
    template_name = 'NoteBoardApp/detail_note.html'
    form_class = UpdateNoteForm

    def form_valid(self, form):
        note_id = self.kwargs.get('pk')
        form = form.save(commit=False)
        category = form.category
        form.save()
        return redirect('category', category)

class SettingsView(FormView):
    template_name = 'NoteBoardApp/settings.html'
    form_class = SettingsForm

    def post(self, request, *args, **kwargs):
        # print(request.session.get('site_color'))
        SiteTheme.set_color(request)
        return redirect('settings')

NoteBoardApp/templates/NoteBoardApp/add_category.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — New Category{% endblock %}

{% block style %}{% static 'css/add_category.css' %}{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="message">
                <p class="message_text">{{ message }}</p>
                <a href="#" class="close">✖</a>
            </div>
        {% endfor %}
    {% endif %}
    <div class="main_block_title">
        <h2>Add New Category</h2>
    </div>
    <form method="POST">
        {% csrf_token %}
        {% for item in form %}
            <p class="form_label">{{ item.label }}:</p>
            <p class="form_item">{{ item }}</p>
        {% endfor %}
        <input type="submit" value="Добавить">
    </form>
    <div class="popular_category">
        <h4 class="popular_category_title">Популярные категории срди пользователей:</h4>
        {% for i in popular_category %}
            <p class="popular_category_item">{{ i.0 }}</p>
        {% endfor %}
    </div>

{% endblock %}

{% block scripts %}
    <script>
        // выделение активной ссылки меню
        $('.add_new_category').css({'backgroundColor': 'var(--link-color_active)'})

        // заносит в поле ввода категории выбранное значение
        $('.popular_category_item').on('click', function (){
            $('#id_name').val(this.textContent)
        })


        let movingBlock = $('.message').hide();

        $(window).on('load', function(){
            movingBlock.slideToggle();
        });

        $('.close').on('click', function (){
            movingBlock.slideToggle();
        });
    </script>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/add_note.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — New Note{% endblock %}

{% block style %}{% static 'css/add_note.css' %}{% endblock %}

{% block content %}
    <div class="main_block_title">
        <h2>Add New Note</h2>
    </div>
    <form method="POST">
        {% csrf_token %}
        {% for item in form %}
            <p class="form_label">{{ item.label }}:</p>
            <p class="form_item">{{ item }}</p>
        {% endfor %}
        <input type="submit" value="Добавить">
    </form>

{% endblock %}

{% block scripts %}
    <script>
    $('.vDateField').attr('type', 'date')
    $('.vTimeField').attr('type', 'time')
    </script>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/all_notes.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — All{% endblock %}

{% block style %}{% static 'css/all_notes.css' %}{% endblock %}

{% block content %}
    {% comment %}
    <div class="add_note">
        <a class="add_note_link" href="{% url 'add_note' %}">✛</a>
    </div>
    {% endcomment %}
    <div class="main_block_title">
        <h2>All</h2>
        <div class="action-but">
            <a class="add_note_link" href="{% url 'add_note' %}">╳</a>
        </div>
    </div>
    <div class="all_notes">
        {% for note in notes %}
            <div class="note">
                {% ifchanged %}<h4 class="notes_date">{{ note.deadline|date:"d F Y" }}</h4>{% endifchanged %}
                {% ifchanged %}<h6 class="notes_category">{{ note.category }}</h6>{% endifchanged %}
                <div class="notes_content">
                    <label class="notes_checkbox">
                        <input type="checkbox" id="{{ note.id }}"
                                {% if note.is_done %}
                                    checked
                                {% endif %}>
                        <span class="notes_title"><a href="{% url 'detail_note' note.id %}">{{ note.title }}</a></span>
                    </label>
                    <p class="notes_deadline">{{ note.deadline|time:"H:i" }}</p>
                </div>

                {% empty %}
                <div class="empty_block">
                <img src="{% static 'img/box.gif' %}" width="50">
                    <p>Тут пока пусто</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script>
    $('document').ready(function (){

        $('.notes_checkbox > input').on("change", function (){

            $.ajax({
                type: 'GET',
                url: {% url 'note_action_ajax' %},
                data: {'checked': this.id},
                success: function (data){
                    console.log(data)
                },
            });
        })
    });

    // стилизация выполненых и невыполненых заданий
    $('input:checkbox').click(function(){
        if ($(this).is(':checked')) {
            $(this).children('span').css('textDecoration', 'line-through');
        } else {
            $(this).children('span').css('textDecoration', 'none');
        }
    });

    // выделение активной ссылки меню
    $('.unchangeable_menu_item:eq(1)').css({'backgroundColor': 'var(--link-color_active)'})
    </script>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}TooDoo{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% block style %}{% endblock %}">
        <link rel="icon" href="{% static 'img/box.svg' %}" type="image/x-icon">
    </head>
    <body>
        <div class="wrapper">
            <nav>
                <div class="search">
                    <input class="search-control" placeholder="Search">
                    <svg version="1.1" class="search-but" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="25px" viewBox="0 0 612.01 612.01" style="enable-background:new 0 0 612.01 612.01;"
	 xml:space="preserve">
                    <g>
                        <g id="_x34__4_">
                            <g>
                                <path class="svg-search" d="M606.209,578.714L448.198,423.228C489.576,378.272,515,318.817,515,253.393C514.98,113.439,399.704,0,257.493,0
                                    C115.282,0,0.006,113.439,0.006,253.393s115.276,253.393,257.487,253.393c61.445,0,117.801-21.253,162.068-56.586
                                    l158.624,156.099c7.729,7.614,20.277,7.614,28.006,0C613.938,598.686,613.938,586.328,606.209,578.714z M257.493,467.8
                                    c-120.326,0-217.869-95.993-217.869-214.407S137.167,38.986,257.493,38.986c120.327,0,217.869,95.993,217.869,214.407
                                    S377.82,467.8,257.493,467.8z"/>
                            </g>
                        </g>
                    </g>
                    </svg>
                </div>
                <ul class="unchangeable_menu">
                    <li class="unchangeable_menu_item">
                        <a class="unchangeable_menu_link" href="{% url 'home' %}">Today</a>
                    </li>
                    <li class="unchangeable_menu_item">
                        <a class="unchangeable_menu_link" href="{% url 'all_notes' %}">All</a>
                    </li>
                    <li class="unchangeable_menu_item">
                        <a class="unchangeable_menu_link" href="#">Scheduled</a>
                    </li>
                </ul>
                <h4 class="changeable_menu_title">List</h4>
                <ul class="changeable_menu">
                    {% for category in categories %}
                        <li class="changeable_menu_item" style="color: {{ category.color }}">
                            <a class="changeable_menu_link" href="{% url 'category' category.get_absolute_url %}">{{ category }}</a>
                        </li>
                    {% endfor %}
                    <li class="add_new_category">
                        <a class="add_new_category_link" href="{% url 'add_category' %}">New list</a>
                    </li>
                </ul>
                <a class="settings" href="{% url 'settings' %}">
                    <img src="{% static 'img/menu.svg' %}" width="30">
                </a>
            </nav>
            <div class="main_block"> <!-- изменить название класса -->
                {% block content %}

                {% endblock %}
            </div>
        </div>
        <!--Подключаем библиотеку-->
	    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script>
                // реализация события нажатия на кнопку "Search"
                $('.search-but').on('click', function (){
                    if ($('.search-control').val() !== '') {
                        let url = 'http://' + window.location.host + '/search/' + $('.search-control').val()
                        window.location.href = url
                    }
                })

                // реализация события нажатия на Enter для поиска
                $('.search-control').keydown(function(e) {
                    if(e.keyCode === 13) {
                        if ($(this).val() !== '') {
                            let url = 'http://' + window.location.host + '/search/' + $(this).val()
                            window.location.href = url
                        }
                    }
                })

                $('.changeable_menu_item').on('click', function (){
                    let suffix = $(this).children('.changeable_menu_link').attr('href')
                    let url = 'http://' + window.location.host + suffix
                        window.location.href = url
                })

                $('.add_new_category').on('click', function (){
                    let suffix = $(this).children('.add_new_category_link').attr('href')
                    let url = 'http://' + window.location.host + suffix
                        window.location.href = url
                })

                $('.search-but').on('mouseover', function (){
                    $('.svg-search').css('fill', '#666')
                })

                $('.search-but').on('mouseout', function (){
                    $('.svg-search').css('fill', '#000')
                })
        </script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

NoteBoardApp/templates/NoteBoardApp/category.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — {{ category }}{% endblock %}

{% block style %}{% static 'css/category.css' %}{% endblock %}

{% block content %}
    <div class="main_block_title">
        <h2>{{ category }}</h2>
        <div class="action-but">
            <a class="delete_category" href="{% url 'delete_category' category.id %}">
                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" width="30" xmlns:xlink="http://www.w3.org/1999/xlink"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<path class="svg-delete" style="fill:#ff6979;" d="M452.923,98.462h-98.462C354.462,44.081,310.38,0,256,0s-98.462,44.081-98.462,98.462H59.077
	c-13.598,0-24.615,11.018-24.615,24.615s11.018,24.615,24.615,24.615h9.846V448c0.059,35.328,28.672,63.941,64,64h246.154
	c35.328-0.059,63.941-28.672,64-64V147.692h9.846c13.598,0,24.615-11.018,24.615-24.615S466.521,98.462,452.923,98.462z M256,49.231
	c27.185,0,49.231,22.046,49.231,49.231h-98.462C206.769,71.276,228.815,49.231,256,49.231z M393.846,448
	c0,8.153-6.617,14.769-14.769,14.769H132.923c-8.153,0-14.769-6.617-14.769-14.769V147.692h275.692V448z"/>
<g>
	<path class="svg-delete" style="fill:#ff6979;" d="M201.846,379.077c-13.598,0-24.615-11.018-24.615-24.615V256c0-13.598,11.018-24.615,24.615-24.615
		s24.615,11.018,24.615,24.615v98.462C226.462,368.059,215.444,379.077,201.846,379.077z"/>
	<path class="svg-delete" style="fill:#ff6979;" d="M310.154,379.077c-13.598,0-24.615-11.018-24.615-24.615V256c0-13.598,11.018-24.615,24.615-24.615
		c13.598,0,24.615,11.018,24.615,24.615v98.462C334.769,368.059,323.751,379.077,310.154,379.077z"/>
</g>
                </svg>
            </a>
            <a class="add_note_link" href="{% url 'add_note_category' category.name %}">╳</a>
        </div>
    </div>
    <div class="all_notes">
        {% for note in notes %}
            <div class="note">
                {% ifchanged %}<h4 class="notes_date">{{ note.deadline|date:"d F Y" }}</h4>{% endifchanged %}
                <div class="notes_content">
                    <label class="notes_checkbox">
                        <input type="checkbox" id="{{ note.id }}"
                                {% if note.is_done %}
                                    checked
                                {% endif %}>
                        <span class="notes_title"><a href="{% url 'detail_note' note.id %}">{{ note.title }}</a></span>
                    </label>
                    <p class="notes_deadline">{{ note.deadline|time:"H:i" }}</p>
                </div>

                {% empty %}
                <div class="empty_block">
                <img src="{% static 'img/box.gif' %}" width="50">
                    <p>Тут пока пусто</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script>
    $('document').ready(function (){

        $('.notes_checkbox > input').on("change", function (){

            $.ajax({
                type: 'GET',
                url: {% url 'note_action_ajax' %},
                data: {'checked': this.id},
                success: function (data){
                    console.log(data)
                },
            });
        })
    });

    // стилизация выполненых и невыполненых заданий
    $('input:checkbox').click(function(){
        if ($(this).is(':checked')) {
            $(this).children('span').css('textDecoration', 'line-through');
        } else {
            $(this).children('span').css('textDecoration', 'none');
        }
    });

    $('.delete_category').on('mouseover', function (){
        $('.svg-delete').css('fill', 'var(--delete-button-hover)')
    })

    $('.delete_category').on('mouseout', function (){
        $('.svg-delete').css('fill', 'var(--delete-button)')
    })

    // выделение активной ссылки меню
    $('.changeable_menu_item:eq({{ position }})').css({'backgroundColor': 'var(--link-color_active)'})
    </script>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/delete_category.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — {{ category }}{% endblock %}

{% block style %}{% static 'css/delete_category.css' %}{% endblock %}

{% block content %}
    <div class="main_block_title">
        <h2>Вы уверены что хотете удалить категорию "{{ object }}"?</h2>
    </div>
    <form method="post">{% csrf_token %}

        <a class="refuse" href="{% url 'category' object %}">Отказаться</a>
        <input type="submit" value="Подтвердить">
    </form>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/delete_note.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — {% endblock %}

{% block style %}{% static 'css/delete_note.css' %}{% endblock %}

{% block content %}
    <div class="main_block_title">
        <h2>Вы уверены что хотете удалить заметку "{{ object }}"?</h2>
    </div>
    <form method="post">{% csrf_token %}
        <a class="refuse" href="{% url 'category' object.category %}">Отказаться</a>
        <input type="submit" value="Подтвердить">
    </form>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/detail_note.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — Detail Note{% endblock %}

{% block style %}{% static 'css/detail_note.css' %}{% endblock %}

{% block content %}
    <div class="main_block_title">
        <h2>Detail Note</h2>
        <a class="delete_note" href="{% url 'delete_note' note.id %}">
            <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" width="30" xmlns:xlink="http://www.w3.org/1999/xlink"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<path class="svg-delete" style="fill:#ff6979;" d="M452.923,98.462h-98.462C354.462,44.081,310.38,0,256,0s-98.462,44.081-98.462,98.462H59.077
	c-13.598,0-24.615,11.018-24.615,24.615s11.018,24.615,24.615,24.615h9.846V448c0.059,35.328,28.672,63.941,64,64h246.154
	c35.328-0.059,63.941-28.672,64-64V147.692h9.846c13.598,0,24.615-11.018,24.615-24.615S466.521,98.462,452.923,98.462z M256,49.231
	c27.185,0,49.231,22.046,49.231,49.231h-98.462C206.769,71.276,228.815,49.231,256,49.231z M393.846,448
	c0,8.153-6.617,14.769-14.769,14.769H132.923c-8.153,0-14.769-6.617-14.769-14.769V147.692h275.692V448z"/>
<g>
	<path class="svg-delete" style="fill:#ff6979;" d="M201.846,379.077c-13.598,0-24.615-11.018-24.615-24.615V256c0-13.598,11.018-24.615,24.615-24.615
		s24.615,11.018,24.615,24.615v98.462C226.462,368.059,215.444,379.077,201.846,379.077z"/>
	<path class="svg-delete" style="fill:#ff6979;" d="M310.154,379.077c-13.598,0-24.615-11.018-24.615-24.615V256c0-13.598,11.018-24.615,24.615-24.615
		c13.598,0,24.615,11.018,24.615,24.615v98.462C334.769,368.059,323.751,379.077,310.154,379.077z"/>
</g>
                </svg>
        </a>
    </div>
    <form method="POST">
        {% csrf_token %}
        {% for item in form %}
            <p class="form_label">{{ item.label }}:</p>
            <p class="form_item">{{ item }}</p>
        {% endfor %}
        <input type="submit" value="Добавить">
    </form>

{% endblock %}

{% block scripts %}
    <script>
    $('.vDateField').attr('type', 'date')
    $('.vTimeField').attr('type', 'time')

    $('.delete_note').on('mouseover', function (){
        $('.svg-delete').css('fill', 'var(--delete-button-hover)')
    })

    $('.delete_note').on('mouseout', function (){
        $('.svg-delete').css('fill', 'var(--delete-button)')
    })
    </script>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/home.html
{% extends 'NoteBoardApp/base.html' %}

{% load static %}

{% block title %}TooDoo — Today{% endblock %}

{% block style %}{% static 'css/home.css' %}{% endblock %}

{% block content %}
    {% comment %}
    <div class="add_note">
        <a class="add_note_link" href="{% url 'add_note' %}">✛</a>
    </div>
    {% endcomment %}
    <div class="main_block_title">
        <h2>Today</h2>
        <div class="action-but">
            <a class="add_note_link" href="{% url 'add_note' %}">╳</a>
        </div>
        <h6>{% now "d F Y" %} года</h6>
    </div>
    <div class="all_notes">
        {% for note in notes %}
            <div class="note">
                {% ifchanged %}<h6 class="notes_category">{{ note.category }}</h6>{% endifchanged %}
                <div class="notes_content">
                    <label class="notes_checkbox">
                        <input type="checkbox" id="{{ note.id }}"
                                {% if note.is_done %}
                                    checked
                                {% endif %}>
                        <span class="notes_title"><a href="{% url 'detail_note' note.id %}">{{ note.title }}</a></span>
                    </label>
                    <p class="notes_deadline">{{ note.deadline|time:"H:i" }}</p>
                </div>
            </div>
            {% empty %}
            <div class="empty_block">
                <img src="{% static 'img/box.gif' %}" width="50">
                <p>Тут пока пусто</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script>
    $('document').ready(function (){

        $('.notes_checkbox > input').on("change", function (){

            $.ajax({
                type: 'GET',
                url: {% url 'note_action_ajax' %},
                data: {'checked': this.id},
                success: function (data){
                },
            });
        })
    });

    // стилизация выполненых и невыполненых заданий

    $('input:checkbox').click(function(){
        if ($(this).is(':checked')) {
            $(this).children('span').css('textDecoration', 'line-through');
        } else {
            $(this).children('span').css('textDecoration', 'none');
        }
    });


    // выделение активной ссылки меню
    $('.unchangeable_menu_item:eq(0)').css({'backgroundColor': 'var(--link-color_active)'})
    </script>
{% endblock %}

NoteBoardApp/templates/NoteBoardApp/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>fsafas</title>
</head>
<body style="background-color: {{ site_color }}">
<form method="post">
    {% csrf_token %}
    {{ form.title }}
    <input type="submit" value="Сохранить">
</form>
</body>
</html>